version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://rafael:password@db:5432/chiara_system
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/vite-project/dist:/usr/share/nginx/html/
    ports:
      - "80:80"     
    depends_on:
      - web
      - frontend
  frontend:
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    volumes:
      - ./frontend/vite-project/dist:/usr/share/nginx/html/  # Serve arquivos estáticos gerados pelo Vite
    ports:
      - "8080:8080"
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
volumes:
  pgdata:

 
